spring:
  application:
    name: service-registry

  config:
    import: "optional:configserver:"
    fail-fast: false

  cloud:
    config:
      uri: http://localhost:9000
      enabled: true

server:
  port: 9001

eureka:
  server:
    enableSelfPreservation: false

